### ISSUE TITLE
Classes vs Functions

### ISSUE THREAD

**Issue by Dog** [exercism/xphp#29]
I know a few of the exercises in xpython were updated from classes with a single function to simply functions. I noticed that xphp has a few exercises where I think it'd make sense to use a function rather than a class. Two examples are hamming and leap. They accept one argument on initialization that could be the argument to the function.

No use case is given where the argument needs to be stored with its instance, or the class later being extended. I think it'd be more appropriate to define them as functions.

Does anyone else have an opinion on this?

**Comment by Dog** [comment]
These are the problems I have left to go through for this issue:

- [ ] bowling
- [ ] clock
- [ ] robot-name
- [ ] wordy

**Comment by petemcfarlane** [comment]
I have re-written wordy as a function #43. 

I don't think bowling, clock or robot-name make sense as functions because they have persisted states that are stored within the instance. What do you think @Dog?

**Comment by kytrinyx** [comment]
Agreed -- I think bowling and robot-name should remain as they are.

**Comment by petemcfarlane** [comment]
What about clock? I think it's hard to add to, subtract from or compare something that doesn't have a state.

**Comment by kytrinyx** [comment]
Yeah, that's my understanding as well. Let's leave clock as is.

**Comment by kytrinyx** [comment]
OK, cool. Closing this--if something comes up later we can always reopen or create a new issue.

Thanks, all!
