### ISSUE TITLE
robot-name instruction unclear

### ISSUE THREAD

**Issue by schorsch3000** [exercism/xphp#54]
Hi,
the readme of this exercise gives two examples of valid names, both containing two uppercase letters.
the test-suite only checks for two letters.
am i supposed to use only uppercase letters? 
in this case the testcase should be changed.
or am i supposed to use lowercase and uppercase letters to increase the uniqe serialnumber-count?
that should be mentioned in the readme.

**Comment by kytrinyx** [comment]
The READMEs are intentionally ambiguous. The test suite is the specification, and there is no need to add complexity that the test suite doesn't call for.

**Comment by schorsch3000** [comment]
So a solution using only uppercase letters is fine, one using only lowercase letters is fine and one using a mix is also fine?

if that is the intention i'm fine with that.
that brings the point of having to work with unnecessary information you deal with every day in a typicly job :)

**Comment by kytrinyx** [comment]
Haha, yeah, story of my life.

I like the restrictions that you added in the new test suite.
