### ISSUE TITLE
Hello World will trigger a warning on php 5.6+

### ISSUE THREAD

**Issue by suralc** [exercism/xphp#94]
The function `helloWorld` is called without passing all required arguments in the tests. This will trigger a warning on 5.6 and later (7.1alpha2 and later throw an exception, currently): 

https://3v4l.org/GOT6G

The function signature should be changed to

`function helloWorld($name = null)`

**Comment by petemcfarlane** [comment]
Whilst this file was only intended to be a skeleton to aid the user, I agree having declared a method with such a signature could be confusing for somebody learning PHP. I've therefore updated the implementation as you suggested, thanks!
